version: '3.1'
services:

  master:
    image: redis:3
  slave:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - master:redis-master
  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000    
    depends_on:
      - master:redis-master
      - slave
